name: Auto Video Generator Workflow



on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Manually trigger the workflow if needed


jobs:
  video-generation:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the latest Python 3 version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the video generation script
      - name: Run the script
        env:
          PAAPI_ACCESS_KEY: ${{ secrets.PAAPI_ACCESS_KEY }}
          PAAPI_SECRET_KEY: ${{ secrets.PAAPI_SECRET_KEY }}
          PAAPI_PARTNER_TAG: ${{ secrets.PAAPI_PARTNER_TAG }}
          PAAPI_HOST: ${{ secrets.PAAPI_HOST }}  # Ensure this is correctly loaded from secrets
          PAAPI_REGION: ${{ secrets.PAAPI_REGION }}  # Ensure this is correctly loaded from secrets
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/main.py

      # Optionally, upload any logs/artifacts
      - name: Upload logs (optional)
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: ./logs/output.log
